from lib.algos.gans import RCGAN, RCWGAN, TimeGAN,MCGAN
from lib.algos.gmmn import GMMN
from lib.algos.sigcwgan import SigCWGAN, SigMCGAN,ProSigGAN,ProSigMCGAN,SigMCGAN_Cat

#ALGOS = dict(SigCWGAN=SigCWGAN, TimeGAN=TimeGAN, RCGAN=RCGAN, GMMN=GMMN, RCWGAN=RCWGAN,MCGAN=MCGAN,MCWGAN_2=MCWGAN_2,MCWGAN_1=MCWGAN_1,MCWGAN_3=MCWGAN_3,MCSWGAN=MCSWGAN,GARCH=GARCH,SigCWGAN_G=SigCWGAN_G)
ALGOS = dict(SigCWGAN=SigCWGAN, TimeGAN=TimeGAN, RCGAN=RCGAN, GMMN=GMMN, RCWGAN=RCWGAN,MCGAN=MCGAN, SigMCGAN= SigMCGAN,ProSigGAN=ProSigGAN,ProSigMCGAN=ProSigMCGAN,SigMCGAN_Cat=SigMCGAN_Cat)
